custom/urls.py
from django.urls import path
from .views import signUpPage,loginPage,homePage,logoutUser,validate_input,houseView,houseDetails
urlpatterns = [
    path("",homePage,name="homepage"),
    path("signup/",signUpPage,name="signup"),
    path("login/",loginPage,name="login"),
    path("logout/",logoutUser,name="signout"),
    path("validate_input/",validate_input,name="validate_input"),
    path("register_house/",houseView, name="house_reg"),
    path("house_details/<int:pk>/",houseDetails, name="house_details")
]

customAuth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("custom.urls"))
]

custom/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser
# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self,first_name,last_name,email,nat_id,dob,user_type,password=None):
        if not nat_id:
            raise ValueError("User cannot sign up without valid ID")
        user=self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            nat_id=nat_id,
            dob=dob,
            user_type=user_type,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,first_name,last_name,email,nat_id,dob,user_type,password=None):
        user= self.create_user(
            first_name=first_name,
            last_name=last_name,
            email=email,
            nat_id=nat_id,
            dob=dob,
            user_type=user_type,
            password=password,
        )
        user.is_admin=True
        user.save(using=self._db)
        return user
class RentUser(AbstractBaseUser):
    USER_TYPE=(
        ("LD","Landlord"),
        ("TN","Tenant")
    )
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    email=models.EmailField(verbose_name="Email Address",unique=True)
    phone_number=models.CharField(max_length=12, null=True)
    nat_id=models.CharField(max_length=8,unique=True)
    dob=models.DateField(verbose_name="Date of Birth")
    user_type=models.CharField(choices=USER_TYPE,max_length=8)
    is_active=models.BooleanField(default=True)
    is_admin=models.BooleanField(default=False)
    objects=UserManager()
    USERNAME_FIELD="nat_id"
    REQUIRED_FIELDS=["first_name","last_name","dob","user_type",'email']

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self,app_label):
        return True
    @property
    def is_staff(self):
        return self.is_admin

    
# support models

class HouseModel(models.Model):
    HOUSE_TYPE=(
        ("BD","BedSitter"),
        ("OB","One Bedroom"),
        ("TB","Two Bedroom"),
        ("THD","Three Bedroom"),
        ("CM","Commercial"),
        ("GH","Guest House"),
    )
    house_name=models.CharField(max_length=30)
    house_location=models.CharField(max_length=20)
    rent_per_month=models.CharField(max_length=10)
    house_type=models.CharField(choices=HOUSE_TYPE,default="BedSitter",max_length=15)
    landlord=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

custom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import RentUser,HouseModel

class RentUserForm(UserCreationForm):
    class Meta:
        model=RentUser
        fields=("nat_id","first_name","last_name","email","dob","user_type","password1","password2")
        widgets={
            "dob":forms.DateInput(attrs={'type':'date'}),
            "email":forms.EmailInput(attrs={"placeholder":"Working Email Address"}),
        }
class HouseForm(forms.ModelForm):
    class Meta:
        model=HouseModel
        fields="__all__"
        exclude=("landlord",)

custom/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from .forms import RentUserForm,HouseForm
from .models import HouseModel
# Create your views here.

def homePage(request):
    houses=HouseModel.objects.all()
    return render(request,"index.html",{"houses":houses})

def signUpPage(request):
    if request.method=="POST":
        form=RentUserForm(request.POST)
        if form.is_valid():
            f_name=form.cleaned_data['first_name']
            form.save()
            messages.success(request,f"Account for {f_name} has been created succesfully.")
            return redirect("login")
    else:
        form=RentUserForm()
    return render(request,"custom/signup.html",{'form':form})

def loginPage(request):
    if request.method=="POST":
        nat_id=request.POST.get("nat_id")
        pswd=request.POST.get("password")
        print(nat_id,pswd)
        user=authenticate(request,username=nat_id,password=pswd)
        if user:
            login(request,user)
            return redirect("homepage")
        else:
            messages.info(request,"Incorrect National Id or password!")
    return render(request,"custom/login.html")

def logoutUser(request):
    logout(request)
    return redirect("homepage")

def houseView(request):
    if request.method=="POST":
        form=HouseForm(request.POST)
        if form.is_valid():
            house=form.cleaned_data["house_name"]
            form=form.save(commit=False)
            form.landlord=request.user
            form.save()
            messages.success(request,f"{house} has been registered successfully")
            return redirect("house_reg")
    else:
        form=HouseForm()
    return render(request,"custom/house.html",{"form":form})

def houseDetails(request,pk):
    house=get_object_or_404(HouseModel,id=pk)
    return render(request,"custom/house_det.html",{"house":house})
# htmx

def validate_input(request):
    return HttpResponse(None)
    

custom/templates/custom/house.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Register your house{% endblock title %}
{% block content %}
<nav class="nav">
    <p class="nav-link">Hello, {{request.user}}</p>
    <a href="{% url 'homepage' %}" class="nav-link">Home</a>
</nav>
<div class="container-fluid">
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label class="form-label">{% render_field field.label_tag %}</label>
            {% render_field field class="form-control" %}
            {% render_field field.errors class="form-text" %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Register House</button>
    </form>
</div>
{% endblock content %}

custom/templates/custom/house_det.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}House details{% endblock title %}
{% block content %}
<div class="container-fluld">
    <a class="nav-link" href="{% url 'homepage' %}">Home</a>
    <h2>House Details</h2>
    <div class="card">
        <h5 class="card-title">{{house.house_name}} is owned by {{house.landlord}}</h5>
        <div class="card-body">
            <ul class="card-text">
                <li>{{house.house_location}}</li>
                <li>{{house.rent_per_month}}</li>
                <li>{{house.get_house_type_display}}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

custom/templates/custom/login.html
{% extends 'base.html' %}
{% block title %}Login Page{% endblock title %}
{% block content %}
<div class="container-fluld">
    <div class="message">
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="nat_id" class="form-label">National ID</label>
                  <input type="text" class="form-control" id="nat_id" name="nat_id" required>
                </div>
                <div class="mb-3">
                  <label for="pswd" class="form-label">Password</label>
                  <input type="password" class="form-control" id="pswd" name="password" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>
{% endblock content %}

custom/templates/custom/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Sign up Page{% endblock title %}
{% block content %}
<div class="container_fluld">
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="nat_id" class="form-label">National ID</label>
                    {% render_field form.nat_id class="form-control" id="nat_id" hx-post="/validate_input/" hx-target="#id_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="id_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name</label>
                    {% render_field form.first_name class="form-control" id="first_name" hx-post="/validate_input/" hx-target="#f_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="f_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name</label>
                    {% render_field form.last_name class="form-control" id="last_name" hx-post="/validate_input/" hx-target="#l_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="l_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email Address</label>
                    {% render_field form.email class="form-control" id="email" hx-post="/validate_input/" hx-target="#e_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="e_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="dob" class="form-label">Date of Birth</label>
                    {% render_field form.dob class="form-control" id="dob" hx-post="/validate_input/" hx-target="#dob_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="dob_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="user_type" class="form-label">User Type</label>
                    {% render_field form.user_type class="form-control" id="user_type" hx-post="/validate_input/" hx-target="#u_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="u_feedback"></div>
                </div>
                <div class="mb-3">
                    <label for="pswd" class="form-label">Password</label>
                    {% render_field form.password1 class="form-control" id="pswd" hx-post="/validate_input/" hx-target="#pswd1_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="pswd1_feedback">
                        <ul>
                            <li>Should have atleast one number.</li>
                            <li>Should have atleast one uppercase and one lowercase.</li>
                            <li>Should have atlease one special symbol.</li>
                            <li>Should be between 8 to 15 characters long.</li>
                        </ul>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="c_pswd" class="form-label">Confirm Password</label>
                    {% render_field form.password2 class="form-control" id="c_pswd" hx-post="/validate_input/" hx-target="#pswd2_feedback" hx-trigger="focusout delay:.01s" %}
                    <div class="form-text" id="pswd2_feedback"></div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href={% static 'main.css' %}>
    <title>{% block title %}Base Template{% endblock title %}</title>
  </head>
  <body>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.8.4" integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock title %}
{% block content %}
<nav class="nav">
    {% if request.user.is_authenticated %}
    <p class="nav-link"> Hello, {{request.user}}.</p>
    {% if request.user.user_type == "LD" %}
        <a class="nav-link" href={% url 'house_reg' %}>Register New House</a>
    {% endif %}
    <a class="nav-link" href="{% url 'signout' %}">Sign Out</a>
    {% else %}
    <a class="nav-link" href="{% url 'login' %}">Login</a>
    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
</nav>
<div class="main">
    <h2>Welcome to RentWithin</h2>
    {% for house in houses %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{house.house_name}}</h5>
            <ul class="card-text">
                <li>{{house.house_location}}</li>
                <li>{{house.rent_per_month}}</li>
                <li>{{house.get_house_type_display}}</li>
            </ul>
            <a href="house_details/{{house.id}}/" class="btn btn-primary">More details</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}